// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getNextFeedtoFetch.sql

package database

import (
	"context"
)

const getNextFeedtoFetch = `-- name: GetNextFeedtoFetch :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_dt FROM feeds 
ORDER BY last_fetched_dt ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetNextFeedtoFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedtoFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedDt,
	)
	return i, err
}
